In [184]:
import numpy as np

In [185]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [186]:
# 1. How many negative numbers are there?

print(a[a<0])
len(a[a<0])

# you can also do "(a<0).sum()"

[-2 -1 -6 -7]


4

In [187]:
# alternative option
(a<0).sum()

4

In [13]:
# 2. How many positive numbers are there?


print(a[a>0])
len(a[a>0])



[ 4 10 12 23  3]


5

In [217]:
# 3. How many even positive numbers are there?

mask = (a % 2 == 0) & (a > 0)
print(mask)

print(a[mask])

len(a[mask])


[ True  True  True False False False False False False False False False]
[ 4 10 12]


3

In [22]:
# 4. If you were to add 3 to each data point, how many positive numbers would there be?

b= a + 3

print(b[b>0])
len(b[b>0])



[ 7 13 15 26  1  2  3  3  3  6]


10

In [189]:
# 5. If you squared each number, what would the new mean and standard deviation be?


print('original array')
print(a)
print(a.mean())
print(a.std())
print('')
c = np.square(a)
print('')
print('new array')
print(c)
print(c.mean())
c.std()




original array
[ 4 10 12 23 -2 -1  0  0  0 -6  3 -7]
3.0
8.06225774829855


new array
[ 16 100 144 529   4   1   0   0   0  36   9  49]
74.0


144.0243035046516

In [190]:
# 6. A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. Center the data set. 
# See this link for more on centering.


d = a.mean()
print('orginal mean')
print(d)

e = a-d
print('new list and new mean')
print(e)
e.mean()



orginal mean
3.0
new list and new mean
[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


0.0

In [58]:
# 7. Calculate the z-score for each data point. Recall that the z-score is given by:


a_mean = a.mean()

a_std = a.std()

f = (a - a_mean)/a_std

f



array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

## Setup 1

In [220]:
# 8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

import numpy as np

# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = sum(a)
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = min(a)
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a)
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = ((sum(a) / (len(a))))
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
# product_of_a = np.prod(a)

product_of_a = 1
for i in a:
    product_of_a *= i





# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = [n**2 for n in a]
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = [n for n in a if n%2]
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = [n for n in a if not n%2]


print(a)
print(sum_of_a)
print(min_of_a)
print(max_of_a)
print(mean_of_a)
print(product_of_a)
print(squares_of_a)
print(odds_in_a)
print(evens_in_a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
55
1
10
5.5
3628800
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[1, 3, 5, 7, 9]
[2, 4, 6, 8, 10]


## Setup 2

In [134]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**

# sum_of_b = 0
# for row in b:
#     sum_of_b += sum(row)

b = np.array(b) 

np.sum(b)


33

In [137]:
# Exercise 2 - refactor the following to use numpy. 
#min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

b.min()

3

In [139]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])


np.max(b)

8

In [140]:
# Exercise 4 - refactor the following using numpy to find the mean of b
# mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

np.mean(b)

5.5

In [145]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
# product_of_b = 1
# for row in b:
#     for number in row:
#         product_of_b *= number

np.prod(b)


20160

In [149]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

np.square(b)


array([[ 9, 16, 25],
       [36, 49, 64]])

In [158]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

b[b % 2 != 0]



array([3, 5, 7])

In [191]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

b[b % 2 == 0]

array([4, 6, 8])

In [159]:
# Exercise 9 - print out the shape of the array b.

np.shape(b)

(2, 3)

In [160]:
# Exercise 10 - transpose the array b.

np.transpose(b) # now its 3 by 2 instead of 2 by 3

array([[3, 6],
       [4, 7],
       [5, 8]])

In [192]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

np.reshape(b, (1,6)) # also can use b.flatten() - method only, not a function

array([[3, 4, 5, 6, 7, 8]])

In [170]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)


b.reshape(6, 1)



array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## Setup 3

In [222]:

c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.

c = np.array(c)

print(c.min())
print(c.max())
print(c.sum())
print(c.prod())



1
9
45
362880


In [223]:
# Exercise 2 - Determine the standard deviation of c.

np.std(c)

2.581988897471611

In [224]:
# Exercise 3 - Determine the variance of c.

np.var(c)

6.666666666666667

In [225]:
# Exercise 4 - Print out the shape of the array c
np.shape(c) # .shape is an attribute not a function you dont need to use ()

(3, 3)

In [226]:

# Exercise 5 - Transpose c and print out transposed result.

np.transpose(c)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [227]:
# Exercise 6 - Get the dot product of the array c with c. 

np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [234]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

print((c.T * c))


(c.T * c).sum()


[[ 1  8 21]
 [ 8 25 48]
 [21 48 81]]


261

In [237]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

print((c.T * c))

(c.T * c).prod()



[[ 1  8 21]
 [ 8 25 48]
 [21 48 81]]


131681894400

## Setup 4

In [238]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

# Exercise 1 - Find the sine of all the numbers in d


d = np.array(d)
d


np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [201]:
# Exercise 2 - Find the cosine of all the numbers in d

np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [202]:
# Exercise 3 - Find the tangent of all the numbers in d

np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [204]:
# Exercise 4 - Find all the negative numbers in d

d[d < 0]

array([-90, -30, -45, -45])

In [205]:
# Exercise 5 - Find all the positive numbers in d

d[d > 0]  # can use mask for these questions

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [206]:
# Exercise 6 - Return an array of only the unique numbers in d.

np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [207]:
# Exercise 7 - Determine how many unique numbers there are in d.

len(np.unique(d))

11

In [239]:
# Exercise 8 - Print out the shape of d.

print(d)
np.shape(d)

[[ 90  30  45   0 120 180]
 [ 45 -90 -30 270  90   0]
 [ 60  45 -45  90 -45 180]]


(3, 6)

In [211]:
# Exercise 9 - Transpose and then print out the shape of d.

print(d.T)
np.shape(d.T)

[[ 90  45  60]
 [ 30 -90  45]
 [ 45 -30 -45]
 [  0 270  90]
 [120  90 -45]
 [180   0 180]]


(6, 3)

In [210]:
# Exercise 10 - Reshape d into an array of 9 x 2


d.reshape(9, 2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])